/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentação;

import Modelo.Protocolo;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author 55159
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    
    private void formWindowOpened (java.awt.event.WindowEvent evt)
    {
        Timer timer = new Timer();
        TimerTask task = new TimerTask(){
            @Override
            public void run()
            {
                lblUmidade.setText(Protocolo.umidade + "%");
                lblTemperatura.setText(Protocolo.temperatura + "ºC");
                lblPrecipitacao.setText(Protocolo.precipitacao + "%");
            }
            
        };
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblUmid = new javax.swing.JLabel();
        lblUmidade = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblPrec = new javax.swing.JLabel();
        lblPrecipitacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblUmid.setText("Umidade");

        lblUmidade.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUmidade.setText("Umidade");

        lblTemp.setText("Temperatura");

        lblTemperatura.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTemperatura.setText("Temperatura");

        lblPrec.setText("Precipitacao");

        lblPrecipitacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPrecipitacao.setText("Precipitacao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUmidade)
                    .addComponent(lblUmid)
                    .addComponent(lblPrec)
                    .addComponent(lblPrecipitacao)
                    .addComponent(lblTemp)
                    .addComponent(lblTemperatura))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblUmid)
                .addGap(18, 18, 18)
                .addComponent(lblUmidade)
                .addGap(36, 36, 36)
                .addComponent(lblTemp)
                .addGap(18, 18, 18)
                .addComponent(lblTemperatura)
                .addGap(33, 33, 33)
                .addComponent(lblPrec)
                .addGap(18, 18, 18)
                .addComponent(lblPrecipitacao)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPrec;
    private javax.swing.JLabel lblPrecipitacao;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblUmid;
    private javax.swing.JLabel lblUmidade;
    // End of variables declaration//GEN-END:variables
}
