/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

/**
 *
 * @author 55159
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mnbExercicios = new javax.swing.JMenuBar();
        mbuExercicios = new javax.swing.JMenu();
        mniFatorial = new javax.swing.JMenuItem();
        mniPrimo = new javax.swing.JMenuItem();
        mniCalculadora = new javax.swing.JMenuItem();
        mniTriangulo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercícios");

        mbuExercicios.setText("Exercícios");

        mniFatorial.setText("Fatorial");
        mniFatorial.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniFatorialActionPerformed(evt);
            }
        });
        mniFatorial.addVetoableChangeListener(new java.beans.VetoableChangeListener()
        {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException
            {
                mniFatorialVetoableChange(evt);
            }
        });
        mbuExercicios.add(mniFatorial);

        mniPrimo.setText("Primo");
        mniPrimo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniPrimoActionPerformed(evt);
            }
        });
        mbuExercicios.add(mniPrimo);

        mniCalculadora.setText("Calculadora");
        mniCalculadora.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniCalculadoraActionPerformed(evt);
            }
        });
        mbuExercicios.add(mniCalculadora);

        mniTriangulo.setText("Triangulo");
        mniTriangulo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniTrianguloActionPerformed(evt);
            }
        });
        mbuExercicios.add(mniTriangulo);

        jMenuItem1.setText("jMenuItem1");
        mbuExercicios.add(jMenuItem1);

        mnbExercicios.add(mbuExercicios);

        setJMenuBar(mnbExercicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCalculadoraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniCalculadoraActionPerformed
    {//GEN-HEADEREND:event_mniCalculadoraActionPerformed
        Calculadora calculadora = new Calculadora(null, true);
        calculadora.setVisible(true);
    }//GEN-LAST:event_mniCalculadoraActionPerformed

    private void mniFatorialVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException//GEN-FIRST:event_mniFatorialVetoableChange
    {//GEN-HEADEREND:event_mniFatorialVetoableChange
    }//GEN-LAST:event_mniFatorialVetoableChange

    private void mniFatorialActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniFatorialActionPerformed
    {//GEN-HEADEREND:event_mniFatorialActionPerformed
        Fatorial fatorial = new Fatorial(null, true);
        fatorial.setVisible(true);
    }//GEN-LAST:event_mniFatorialActionPerformed

    private void mniPrimoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniPrimoActionPerformed
    {//GEN-HEADEREND:event_mniPrimoActionPerformed
        Primo primo = new Primo(null, true);
        primo.setVisible(true);
        
    }//GEN-LAST:event_mniPrimoActionPerformed

    private void mniTrianguloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniTrianguloActionPerformed
    {//GEN-HEADEREND:event_mniTrianguloActionPerformed
        Triangulo triangulo = new Triangulo(null, true);
        triangulo.setVisible(true);
    }//GEN-LAST:event_mniTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mbuExercicios;
    private javax.swing.JMenuBar mnbExercicios;
    private javax.swing.JMenuItem mniCalculadora;
    private javax.swing.JMenuItem mniFatorial;
    private javax.swing.JMenuItem mniPrimo;
    private javax.swing.JMenuItem mniTriangulo;
    // End of variables declaration//GEN-END:variables
}
